/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/ngap-16.2.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -D /home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/h`
 */

#ifndef	_NGAP_AreaScopeOfMDT_NR_H_
#define	_NGAP_AreaScopeOfMDT_NR_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NGAP_CellBasedMDT-NR.h"
#include "NGAP_TABasedMDT.h"
#include <NULL.h>
#include "NGAP_TAIBasedMDT.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_AreaScopeOfMDT_NR_PR {
	NGAP_AreaScopeOfMDT_NR_PR_NOTHING,	/* No components present */
	NGAP_AreaScopeOfMDT_NR_PR_cellBased,
	NGAP_AreaScopeOfMDT_NR_PR_tABased,
	NGAP_AreaScopeOfMDT_NR_PR_pLMNWide,
	NGAP_AreaScopeOfMDT_NR_PR_tAIBased
	/* Extensions may appear below */
	
} NGAP_AreaScopeOfMDT_NR_PR;

/* NGAP_AreaScopeOfMDT-NR */
typedef struct NGAP_AreaScopeOfMDT_NR {
	NGAP_AreaScopeOfMDT_NR_PR present;
	union NGAP_AreaScopeOfMDT_NR_u {
		NGAP_CellBasedMDT_NR_t	 cellBased;
		NGAP_TABasedMDT_t	 tABased;
		NULL_t	 pLMNWide;
		NGAP_TAIBasedMDT_t	 tAIBased;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_AreaScopeOfMDT_NR_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_AreaScopeOfMDT_NR;
extern asn_CHOICE_specifics_t asn_SPC_NGAP_AreaScopeOfMDT_NR_specs_1;
extern asn_TYPE_member_t asn_MBR_NGAP_AreaScopeOfMDT_NR_1[4];
extern asn_per_constraints_t asn_PER_type_NGAP_AreaScopeOfMDT_NR_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_AreaScopeOfMDT_NR_H_ */
#include <asn_internal.h>
