/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/ngap-16.2.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -D /home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/h`
 */

#ifndef	_NGAP_NPN_Support_H_
#define	_NGAP_NPN_Support_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NGAP_NID.h"
#include "NGAP_ProtocolIE-SingleContainer.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_NPN_Support_PR {
	NGAP_NPN_Support_PR_NOTHING,	/* No components present */
	NGAP_NPN_Support_PR_sNPN,
	NGAP_NPN_Support_PR_choice_Extensions
} NGAP_NPN_Support_PR;

/* NGAP_NPN-Support */
typedef struct NGAP_NPN_Support {
	NGAP_NPN_Support_PR present;
	union NGAP_NPN_Support_u {
		NGAP_NID_t	 sNPN;
		NGAP_ProtocolIE_SingleContainer_9337P24_t	 choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_NPN_Support_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_NPN_Support;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_NPN_Support_H_ */
#include <asn_internal.h>
