/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/ngap-16.2.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -D /home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/h`
 */

#ifndef	_NGAP_WarningAreaList_H_
#define	_NGAP_WarningAreaList_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NGAP_EUTRA-CGIListForWarning.h"
#include "NGAP_NR-CGIListForWarning.h"
#include "NGAP_TAIListForWarning.h"
#include "NGAP_EmergencyAreaIDList.h"
#include "NGAP_ProtocolIE-SingleContainer.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_WarningAreaList_PR {
	NGAP_WarningAreaList_PR_NOTHING,	/* No components present */
	NGAP_WarningAreaList_PR_eUTRA_CGIListForWarning,
	NGAP_WarningAreaList_PR_nR_CGIListForWarning,
	NGAP_WarningAreaList_PR_tAIListForWarning,
	NGAP_WarningAreaList_PR_emergencyAreaIDList,
	NGAP_WarningAreaList_PR_choice_Extensions
} NGAP_WarningAreaList_PR;

/* NGAP_WarningAreaList */
typedef struct NGAP_WarningAreaList {
	NGAP_WarningAreaList_PR present;
	union NGAP_WarningAreaList_u {
		NGAP_EUTRA_CGIListForWarning_t	 eUTRA_CGIListForWarning;
		NGAP_NR_CGIListForWarning_t	 nR_CGIListForWarning;
		NGAP_TAIListForWarning_t	 tAIListForWarning;
		NGAP_EmergencyAreaIDList_t	 emergencyAreaIDList;
		NGAP_ProtocolIE_SingleContainer_9337P43_t	 choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_WarningAreaList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_WarningAreaList;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_WarningAreaList_H_ */
#include <asn_internal.h>
