/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/ngap-16.2.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -D /home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/h`
 */

#ifndef	_NGAP_SONInformationReport_H_
#define	_NGAP_SONInformationReport_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NGAP_FailureIndication.h"
#include "NGAP_HOReport.h"
#include "NGAP_ProtocolIE-SingleContainer.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_SONInformationReport_PR {
	NGAP_SONInformationReport_PR_NOTHING,	/* No components present */
	NGAP_SONInformationReport_PR_failureIndicationInformation,
	NGAP_SONInformationReport_PR_hOReportInformation,
	NGAP_SONInformationReport_PR_choice_Extensions
} NGAP_SONInformationReport_PR;

/* NGAP_SONInformationReport */
typedef struct NGAP_SONInformationReport {
	NGAP_SONInformationReport_PR present;
	union NGAP_SONInformationReport_u {
		NGAP_FailureIndication_t	 failureIndicationInformation;
		NGAP_HOReport_t	 hOReportInformation;
		NGAP_ProtocolIE_SingleContainer_9337P30_t	 choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_SONInformationReport_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_SONInformationReport;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_SONInformationReport_H_ */
#include <asn_internal.h>
