/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/ngap-16.2.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -D /home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/h`
 */

#ifndef	_NGAP_UEPagingIdentity_H_
#define	_NGAP_UEPagingIdentity_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NGAP_FiveG-S-TMSI.h"
#include "NGAP_ProtocolIE-SingleContainer.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_UEPagingIdentity_PR {
	NGAP_UEPagingIdentity_PR_NOTHING,	/* No components present */
	NGAP_UEPagingIdentity_PR_fiveG_S_TMSI,
	NGAP_UEPagingIdentity_PR_choice_Extensions
} NGAP_UEPagingIdentity_PR;

/* NGAP_UEPagingIdentity */
typedef struct NGAP_UEPagingIdentity {
	NGAP_UEPagingIdentity_PR present;
	union NGAP_UEPagingIdentity_u {
		NGAP_FiveG_S_TMSI_t	 fiveG_S_TMSI;
		NGAP_ProtocolIE_SingleContainer_9337P37_t	 choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_UEPagingIdentity_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_UEPagingIdentity;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_UEPagingIdentity_H_ */
#include <asn_internal.h>
