/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/ngap-16.2.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -D /home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/h`
 */

#ifndef	_NGAP_PagingProbabilityInformation_H_
#define	_NGAP_PagingProbabilityInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_PagingProbabilityInformation {
	NGAP_PagingProbabilityInformation_p00	= 0,
	NGAP_PagingProbabilityInformation_p05	= 1,
	NGAP_PagingProbabilityInformation_p10	= 2,
	NGAP_PagingProbabilityInformation_p15	= 3,
	NGAP_PagingProbabilityInformation_p20	= 4,
	NGAP_PagingProbabilityInformation_p25	= 5,
	NGAP_PagingProbabilityInformation_p30	= 6,
	NGAP_PagingProbabilityInformation_p35	= 7,
	NGAP_PagingProbabilityInformation_p40	= 8,
	NGAP_PagingProbabilityInformation_p45	= 9,
	NGAP_PagingProbabilityInformation_p50	= 10,
	NGAP_PagingProbabilityInformation_p55	= 11,
	NGAP_PagingProbabilityInformation_p60	= 12,
	NGAP_PagingProbabilityInformation_p65	= 13,
	NGAP_PagingProbabilityInformation_p70	= 14,
	NGAP_PagingProbabilityInformation_p75	= 15,
	NGAP_PagingProbabilityInformation_p80	= 16,
	NGAP_PagingProbabilityInformation_p85	= 17,
	NGAP_PagingProbabilityInformation_p90	= 18,
	NGAP_PagingProbabilityInformation_p95	= 19,
	NGAP_PagingProbabilityInformation_p100	= 20
	/*
	 * Enumeration is extensible
	 */
} e_NGAP_PagingProbabilityInformation;

/* NGAP_PagingProbabilityInformation */
typedef long	 NGAP_PagingProbabilityInformation_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NGAP_PagingProbabilityInformation_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_PagingProbabilityInformation;
extern const asn_INTEGER_specifics_t asn_SPC_NGAP_PagingProbabilityInformation_specs_1;
asn_struct_free_f NGAP_PagingProbabilityInformation_free;
asn_struct_print_f NGAP_PagingProbabilityInformation_print;
asn_constr_check_f NGAP_PagingProbabilityInformation_constraint;
ber_type_decoder_f NGAP_PagingProbabilityInformation_decode_ber;
der_type_encoder_f NGAP_PagingProbabilityInformation_encode_der;
xer_type_decoder_f NGAP_PagingProbabilityInformation_decode_xer;
xer_type_encoder_f NGAP_PagingProbabilityInformation_encode_xer;
per_type_decoder_f NGAP_PagingProbabilityInformation_decode_uper;
per_type_encoder_f NGAP_PagingProbabilityInformation_encode_uper;
per_type_decoder_f NGAP_PagingProbabilityInformation_decode_aper;
per_type_encoder_f NGAP_PagingProbabilityInformation_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_PagingProbabilityInformation_H_ */
#include <asn_internal.h>
