/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/ngap-16.2.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -D /home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/h`
 */

#ifndef	_NGAP_UESecurityCapabilities_H_
#define	_NGAP_UESecurityCapabilities_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NGAP_NRencryptionAlgorithms.h"
#include "NGAP_NRintegrityProtectionAlgorithms.h"
#include "NGAP_EUTRAencryptionAlgorithms.h"
#include "NGAP_EUTRAintegrityProtectionAlgorithms.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NGAP_ProtocolExtensionContainer;

/* NGAP_UESecurityCapabilities */
typedef struct NGAP_UESecurityCapabilities {
	NGAP_NRencryptionAlgorithms_t	 nRencryptionAlgorithms;
	NGAP_NRintegrityProtectionAlgorithms_t	 nRintegrityProtectionAlgorithms;
	NGAP_EUTRAencryptionAlgorithms_t	 eUTRAencryptionAlgorithms;
	NGAP_EUTRAintegrityProtectionAlgorithms_t	 eUTRAintegrityProtectionAlgorithms;
	struct NGAP_ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_UESecurityCapabilities_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_UESecurityCapabilities;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_UESecurityCapabilities_H_ */
#include <asn_internal.h>
