/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/ngap-16.2.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -D /home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/h`
 */

#ifndef	_NGAP_BroadcastCompletedAreaList_H_
#define	_NGAP_BroadcastCompletedAreaList_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NGAP_CellIDBroadcastEUTRA.h"
#include "NGAP_TAIBroadcastEUTRA.h"
#include "NGAP_EmergencyAreaIDBroadcastEUTRA.h"
#include "NGAP_CellIDBroadcastNR.h"
#include "NGAP_TAIBroadcastNR.h"
#include "NGAP_EmergencyAreaIDBroadcastNR.h"
#include "NGAP_ProtocolIE-SingleContainer.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_BroadcastCompletedAreaList_PR {
	NGAP_BroadcastCompletedAreaList_PR_NOTHING,	/* No components present */
	NGAP_BroadcastCompletedAreaList_PR_cellIDBroadcastEUTRA,
	NGAP_BroadcastCompletedAreaList_PR_tAIBroadcastEUTRA,
	NGAP_BroadcastCompletedAreaList_PR_emergencyAreaIDBroadcastEUTRA,
	NGAP_BroadcastCompletedAreaList_PR_cellIDBroadcastNR,
	NGAP_BroadcastCompletedAreaList_PR_tAIBroadcastNR,
	NGAP_BroadcastCompletedAreaList_PR_emergencyAreaIDBroadcastNR,
	NGAP_BroadcastCompletedAreaList_PR_choice_Extensions
} NGAP_BroadcastCompletedAreaList_PR;

/* NGAP_BroadcastCompletedAreaList */
typedef struct NGAP_BroadcastCompletedAreaList {
	NGAP_BroadcastCompletedAreaList_PR present;
	union NGAP_BroadcastCompletedAreaList_u {
		NGAP_CellIDBroadcastEUTRA_t	 cellIDBroadcastEUTRA;
		NGAP_TAIBroadcastEUTRA_t	 tAIBroadcastEUTRA;
		NGAP_EmergencyAreaIDBroadcastEUTRA_t	 emergencyAreaIDBroadcastEUTRA;
		NGAP_CellIDBroadcastNR_t	 cellIDBroadcastNR;
		NGAP_TAIBroadcastNR_t	 tAIBroadcastNR;
		NGAP_EmergencyAreaIDBroadcastNR_t	 emergencyAreaIDBroadcastNR;
		NGAP_ProtocolIE_SingleContainer_9337P2_t	 choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_BroadcastCompletedAreaList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_BroadcastCompletedAreaList;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_BroadcastCompletedAreaList_H_ */
#include <asn_internal.h>
