/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/ngap-16.2.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -D /home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/h`
 */

#include "NGAP_EventTrigger.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static asn_per_constraints_t asn_PER_type_NGAP_outOfCoverage_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  0,  0,  0,  0 }	/* (0..0,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_NGAP_EventTrigger_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_NGAP_outOfCoverage_value2enum_2[] = {
	{ 0,	4,	"true" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_NGAP_outOfCoverage_enum2value_2[] = {
	0	/* true(0) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_NGAP_outOfCoverage_specs_2 = {
	asn_MAP_NGAP_outOfCoverage_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_NGAP_outOfCoverage_enum2value_2,	/* N => "tag"; sorted by N */
	1,	/* Number of elements in the maps */
	2,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_NGAP_outOfCoverage_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_NGAP_outOfCoverage_2 = {
	"outOfCoverage",
	"outOfCoverage",
	&asn_OP_NativeEnumerated,
	asn_DEF_NGAP_outOfCoverage_tags_2,
	sizeof(asn_DEF_NGAP_outOfCoverage_tags_2)
		/sizeof(asn_DEF_NGAP_outOfCoverage_tags_2[0]) - 1, /* 1 */
	asn_DEF_NGAP_outOfCoverage_tags_2,	/* Same as above */
	sizeof(asn_DEF_NGAP_outOfCoverage_tags_2)
		/sizeof(asn_DEF_NGAP_outOfCoverage_tags_2[0]), /* 2 */
	{ 0, &asn_PER_type_NGAP_outOfCoverage_constr_2, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_NGAP_outOfCoverage_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_NGAP_EventTrigger_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NGAP_EventTrigger, choice.outOfCoverage),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_outOfCoverage_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"outOfCoverage"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NGAP_EventTrigger, choice.eventL1LoggedMDTConfig),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_EventL1LoggedMDTConfig,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eventL1LoggedMDTConfig"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_NGAP_EventTrigger_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* outOfCoverage */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* eventL1LoggedMDTConfig */
};
asn_CHOICE_specifics_t asn_SPC_NGAP_EventTrigger_specs_1 = {
	sizeof(struct NGAP_EventTrigger),
	offsetof(struct NGAP_EventTrigger, _asn_ctx),
	offsetof(struct NGAP_EventTrigger, present),
	sizeof(((struct NGAP_EventTrigger *)0)->present),
	asn_MAP_NGAP_EventTrigger_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_NGAP_EventTrigger = {
	"EventTrigger",
	"EventTrigger",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_NGAP_EventTrigger_constr_1, CHOICE_constraint },
	asn_MBR_NGAP_EventTrigger_1,
	2,	/* Elements count */
	&asn_SPC_NGAP_EventTrigger_specs_1	/* Additional specs */
};

