/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/ngap-16.2.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -D /home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/h`
 */

#ifndef	_NGAP_UserLocationInformation_H_
#define	_NGAP_UserLocationInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NGAP_UserLocationInformationEUTRA.h"
#include "NGAP_UserLocationInformationNR.h"
#include "NGAP_UserLocationInformationN3IWF.h"
#include "NGAP_ProtocolIE-SingleContainer.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_UserLocationInformation_PR {
	NGAP_UserLocationInformation_PR_NOTHING,	/* No components present */
	NGAP_UserLocationInformation_PR_userLocationInformationEUTRA,
	NGAP_UserLocationInformation_PR_userLocationInformationNR,
	NGAP_UserLocationInformation_PR_userLocationInformationN3IWF,
	NGAP_UserLocationInformation_PR_choice_Extensions
} NGAP_UserLocationInformation_PR;

/* NGAP_UserLocationInformation */
typedef struct NGAP_UserLocationInformation {
	NGAP_UserLocationInformation_PR present;
	union NGAP_UserLocationInformation_u {
		NGAP_UserLocationInformationEUTRA_t	 userLocationInformationEUTRA;
		NGAP_UserLocationInformationNR_t	 userLocationInformationNR;
		NGAP_UserLocationInformationN3IWF_t	 userLocationInformationN3IWF;
		NGAP_ProtocolIE_SingleContainer_9337P40_t	 choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_UserLocationInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_UserLocationInformation;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_UserLocationInformation_H_ */
#include <asn_internal.h>
