/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/ngap-16.2.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -D /home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/h`
 */

#ifndef	_NGAP_TargetID_H_
#define	_NGAP_TargetID_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NGAP_TargetRANNodeID.h"
#include "NGAP_TargeteNB-ID.h"
#include "NGAP_ProtocolIE-SingleContainer.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_TargetID_PR {
	NGAP_TargetID_PR_NOTHING,	/* No components present */
	NGAP_TargetID_PR_targetRANNodeID,
	NGAP_TargetID_PR_targeteNB_ID,
	NGAP_TargetID_PR_choice_Extensions
} NGAP_TargetID_PR;

/* NGAP_TargetID */
typedef struct NGAP_TargetID {
	NGAP_TargetID_PR present;
	union NGAP_TargetID_u {
		NGAP_TargetRANNodeID_t	 targetRANNodeID;
		NGAP_TargeteNB_ID_t	 targeteNB_ID;
		NGAP_ProtocolIE_SingleContainer_9337P31_t	 choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_TargetID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_TargetID;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_TargetID_H_ */
#include <asn_internal.h>
