/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/ngap-16.2.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -D /home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/h`
 */

#ifndef	_NGAP_UEHistoryInformationFromTheUE_H_
#define	_NGAP_UEHistoryInformationFromTheUE_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NGAP_NRMobilityHistoryReport.h"
#include "NGAP_ProtocolIE-SingleContainer.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_UEHistoryInformationFromTheUE_PR {
	NGAP_UEHistoryInformationFromTheUE_PR_NOTHING,	/* No components present */
	NGAP_UEHistoryInformationFromTheUE_PR_nR,
	NGAP_UEHistoryInformationFromTheUE_PR_choice_Extensions
} NGAP_UEHistoryInformationFromTheUE_PR;

/* NGAP_UEHistoryInformationFromTheUE */
typedef struct NGAP_UEHistoryInformationFromTheUE {
	NGAP_UEHistoryInformationFromTheUE_PR present;
	union NGAP_UEHistoryInformationFromTheUE_u {
		NGAP_NRMobilityHistoryReport_t	 nR;
		NGAP_ProtocolIE_SingleContainer_9337P34_t	 choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_UEHistoryInformationFromTheUE_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_UEHistoryInformationFromTheUE;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_UEHistoryInformationFromTheUE_H_ */
#include <asn_internal.h>
