/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-Containers"
 * 	found in "/home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/ngap-16.2.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -D /home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/h`
 */

#include "NGAP_ProtocolIE-SingleContainer.h"

/*
 * This type is implemented using NGAP_AMFPagingTarget_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_BroadcastCancelledAreaList_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_BroadcastCompletedAreaList_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_CandidateCell_Item_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_Cause_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_CellIDListForRestart_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_CPTransportLayerInformation_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_DRBStatusDL_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_DRBStatusUL_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_ProcedureStageChoice_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_ENB_ID_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_GlobalRANNodeID_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_GNB_ID_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_IntersystemSONTransferType_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_IntersystemSONInformation_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_IntersystemSONInformationReport_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_InterSystemHandoverReportType_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_LastVisitedCellInformation_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_N3IWF_ID_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_NgENB_ID_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_NGRAN_CGI_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_NPN_AccessInformation_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_NPN_MobilityInformation_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_NPN_PagingAssistanceInformation_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_NPN_Support_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_OverloadResponse_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_PWSFailedCellIDList_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_QosCharacteristics_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_ResetType_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_SONInformation_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_SONInformationReport_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_TargetID_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_TNGF_ID_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_TWIF_ID_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_UEHistoryInformationFromTheUE_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_UEIdentityIndexValue_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_UE_NGAP_IDs_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_UEPagingIdentity_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_UERLFReportContainer_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_UPTransportLayerInformation_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_UserLocationInformation_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_UserLocationInformationW_AGF_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_W_AGF_ID_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NGAP_WarningAreaList_ExtIEs,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P0_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P0 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P0_tags_1,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P0_tags_1)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P0_tags_1[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P0_tags_1,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P0_tags_1)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P0_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_AMFPagingTarget_ExtIEs_1,
	3,	/* Elements count */
	&asn_SPC_NGAP_AMFPagingTarget_ExtIEs_specs_1	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P1_tags_2[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P1 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P1_tags_2,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P1_tags_2)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P1_tags_2[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P1_tags_2,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P1_tags_2)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P1_tags_2[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_BroadcastCancelledAreaList_ExtIEs_5,
	3,	/* Elements count */
	&asn_SPC_NGAP_BroadcastCancelledAreaList_ExtIEs_specs_5	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P2_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P2 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P2_tags_3,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P2_tags_3)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P2_tags_3[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P2_tags_3,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P2_tags_3)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P2_tags_3[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_BroadcastCompletedAreaList_ExtIEs_9,
	3,	/* Elements count */
	&asn_SPC_NGAP_BroadcastCompletedAreaList_ExtIEs_specs_9	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P3_tags_4[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P3 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P3_tags_4,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P3_tags_4)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P3_tags_4[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P3_tags_4,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P3_tags_4)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P3_tags_4[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_CandidateCell_Item_ExtIEs_13,
	3,	/* Elements count */
	&asn_SPC_NGAP_CandidateCell_Item_ExtIEs_specs_13	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P4_tags_5[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P4 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P4_tags_5,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P4_tags_5)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P4_tags_5[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P4_tags_5,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P4_tags_5)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P4_tags_5[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_Cause_ExtIEs_17,
	3,	/* Elements count */
	&asn_SPC_NGAP_Cause_ExtIEs_specs_17	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P5_tags_6[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P5 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P5_tags_6,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P5_tags_6)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P5_tags_6[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P5_tags_6,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P5_tags_6)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P5_tags_6[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_CellIDListForRestart_ExtIEs_21,
	3,	/* Elements count */
	&asn_SPC_NGAP_CellIDListForRestart_ExtIEs_specs_21	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P6_tags_7[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P6 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P6_tags_7,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P6_tags_7)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P6_tags_7[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P6_tags_7,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P6_tags_7)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P6_tags_7[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_CPTransportLayerInformation_ExtIEs_25,
	3,	/* Elements count */
	&asn_SPC_NGAP_CPTransportLayerInformation_ExtIEs_specs_25	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P7_tags_8[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P7 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P7_tags_8,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P7_tags_8)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P7_tags_8[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P7_tags_8,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P7_tags_8)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P7_tags_8[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_DRBStatusDL_ExtIEs_29,
	3,	/* Elements count */
	&asn_SPC_NGAP_DRBStatusDL_ExtIEs_specs_29	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P8_tags_9[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P8 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P8_tags_9,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P8_tags_9)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P8_tags_9[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P8_tags_9,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P8_tags_9)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P8_tags_9[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_DRBStatusUL_ExtIEs_33,
	3,	/* Elements count */
	&asn_SPC_NGAP_DRBStatusUL_ExtIEs_specs_33	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P9_tags_10[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P9 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P9_tags_10,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P9_tags_10)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P9_tags_10[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P9_tags_10,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P9_tags_10)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P9_tags_10[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_ProcedureStageChoice_ExtIEs_37,
	3,	/* Elements count */
	&asn_SPC_NGAP_ProcedureStageChoice_ExtIEs_specs_37	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P10_tags_11[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P10 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P10_tags_11,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P10_tags_11)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P10_tags_11[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P10_tags_11,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P10_tags_11)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P10_tags_11[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_ENB_ID_ExtIEs_41,
	3,	/* Elements count */
	&asn_SPC_NGAP_ENB_ID_ExtIEs_specs_41	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P11_tags_12[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P11 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P11_tags_12,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P11_tags_12)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P11_tags_12[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P11_tags_12,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P11_tags_12)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P11_tags_12[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_GlobalRANNodeID_ExtIEs_45,
	3,	/* Elements count */
	&asn_SPC_NGAP_GlobalRANNodeID_ExtIEs_specs_45	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P12_tags_13[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P12 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P12_tags_13,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P12_tags_13)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P12_tags_13[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P12_tags_13,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P12_tags_13)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P12_tags_13[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_GNB_ID_ExtIEs_49,
	3,	/* Elements count */
	&asn_SPC_NGAP_GNB_ID_ExtIEs_specs_49	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P13_tags_14[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P13 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P13_tags_14,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P13_tags_14)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P13_tags_14[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P13_tags_14,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P13_tags_14)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P13_tags_14[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_IntersystemSONTransferType_ExtIEs_53,
	3,	/* Elements count */
	&asn_SPC_NGAP_IntersystemSONTransferType_ExtIEs_specs_53	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P14_tags_15[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P14 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P14_tags_15,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P14_tags_15)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P14_tags_15[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P14_tags_15,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P14_tags_15)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P14_tags_15[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_IntersystemSONInformation_ExtIEs_57,
	3,	/* Elements count */
	&asn_SPC_NGAP_IntersystemSONInformation_ExtIEs_specs_57	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P15_tags_16[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P15 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P15_tags_16,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P15_tags_16)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P15_tags_16[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P15_tags_16,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P15_tags_16)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P15_tags_16[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_IntersystemSONInformationReport_ExtIEs_61,
	3,	/* Elements count */
	&asn_SPC_NGAP_IntersystemSONInformationReport_ExtIEs_specs_61	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P16_tags_17[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P16 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P16_tags_17,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P16_tags_17)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P16_tags_17[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P16_tags_17,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P16_tags_17)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P16_tags_17[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_InterSystemHandoverReportType_ExtIEs_65,
	3,	/* Elements count */
	&asn_SPC_NGAP_InterSystemHandoverReportType_ExtIEs_specs_65	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P17_tags_18[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P17 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P17_tags_18,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P17_tags_18)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P17_tags_18[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P17_tags_18,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P17_tags_18)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P17_tags_18[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_LastVisitedCellInformation_ExtIEs_69,
	3,	/* Elements count */
	&asn_SPC_NGAP_LastVisitedCellInformation_ExtIEs_specs_69	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P18_tags_19[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P18 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P18_tags_19,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P18_tags_19)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P18_tags_19[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P18_tags_19,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P18_tags_19)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P18_tags_19[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_N3IWF_ID_ExtIEs_73,
	3,	/* Elements count */
	&asn_SPC_NGAP_N3IWF_ID_ExtIEs_specs_73	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P19_tags_20[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P19 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P19_tags_20,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P19_tags_20)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P19_tags_20[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P19_tags_20,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P19_tags_20)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P19_tags_20[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_NgENB_ID_ExtIEs_77,
	3,	/* Elements count */
	&asn_SPC_NGAP_NgENB_ID_ExtIEs_specs_77	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P20_tags_21[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P20 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P20_tags_21,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P20_tags_21)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P20_tags_21[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P20_tags_21,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P20_tags_21)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P20_tags_21[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_NGRAN_CGI_ExtIEs_81,
	3,	/* Elements count */
	&asn_SPC_NGAP_NGRAN_CGI_ExtIEs_specs_81	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P21_tags_22[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P21 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P21_tags_22,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P21_tags_22)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P21_tags_22[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P21_tags_22,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P21_tags_22)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P21_tags_22[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_NPN_AccessInformation_ExtIEs_85,
	3,	/* Elements count */
	&asn_SPC_NGAP_NPN_AccessInformation_ExtIEs_specs_85	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P22_tags_23[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P22 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P22_tags_23,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P22_tags_23)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P22_tags_23[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P22_tags_23,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P22_tags_23)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P22_tags_23[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_NPN_MobilityInformation_ExtIEs_89,
	3,	/* Elements count */
	&asn_SPC_NGAP_NPN_MobilityInformation_ExtIEs_specs_89	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P23_tags_24[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P23 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P23_tags_24,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P23_tags_24)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P23_tags_24[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P23_tags_24,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P23_tags_24)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P23_tags_24[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_NPN_PagingAssistanceInformation_ExtIEs_93,
	3,	/* Elements count */
	&asn_SPC_NGAP_NPN_PagingAssistanceInformation_ExtIEs_specs_93	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P24_tags_25[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P24 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P24_tags_25,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P24_tags_25)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P24_tags_25[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P24_tags_25,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P24_tags_25)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P24_tags_25[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_NPN_Support_ExtIEs_97,
	3,	/* Elements count */
	&asn_SPC_NGAP_NPN_Support_ExtIEs_specs_97	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P25_tags_26[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P25 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P25_tags_26,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P25_tags_26)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P25_tags_26[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P25_tags_26,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P25_tags_26)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P25_tags_26[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_OverloadResponse_ExtIEs_101,
	3,	/* Elements count */
	&asn_SPC_NGAP_OverloadResponse_ExtIEs_specs_101	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P26_tags_27[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P26 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P26_tags_27,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P26_tags_27)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P26_tags_27[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P26_tags_27,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P26_tags_27)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P26_tags_27[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_PWSFailedCellIDList_ExtIEs_105,
	3,	/* Elements count */
	&asn_SPC_NGAP_PWSFailedCellIDList_ExtIEs_specs_105	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P27_tags_28[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P27 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P27_tags_28,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P27_tags_28)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P27_tags_28[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P27_tags_28,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P27_tags_28)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P27_tags_28[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_QosCharacteristics_ExtIEs_109,
	3,	/* Elements count */
	&asn_SPC_NGAP_QosCharacteristics_ExtIEs_specs_109	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P28_tags_29[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P28 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P28_tags_29,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P28_tags_29)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P28_tags_29[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P28_tags_29,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P28_tags_29)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P28_tags_29[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_ResetType_ExtIEs_113,
	3,	/* Elements count */
	&asn_SPC_NGAP_ResetType_ExtIEs_specs_113	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P29_tags_30[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P29 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P29_tags_30,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P29_tags_30)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P29_tags_30[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P29_tags_30,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P29_tags_30)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P29_tags_30[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_SONInformation_ExtIEs_117,
	3,	/* Elements count */
	&asn_SPC_NGAP_SONInformation_ExtIEs_specs_117	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P30_tags_31[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P30 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P30_tags_31,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P30_tags_31)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P30_tags_31[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P30_tags_31,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P30_tags_31)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P30_tags_31[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_SONInformationReport_ExtIEs_121,
	3,	/* Elements count */
	&asn_SPC_NGAP_SONInformationReport_ExtIEs_specs_121	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P31_tags_32[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P31 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P31_tags_32,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P31_tags_32)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P31_tags_32[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P31_tags_32,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P31_tags_32)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P31_tags_32[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_TargetID_ExtIEs_125,
	3,	/* Elements count */
	&asn_SPC_NGAP_TargetID_ExtIEs_specs_125	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P32_tags_33[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P32 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P32_tags_33,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P32_tags_33)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P32_tags_33[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P32_tags_33,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P32_tags_33)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P32_tags_33[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_TNGF_ID_ExtIEs_129,
	3,	/* Elements count */
	&asn_SPC_NGAP_TNGF_ID_ExtIEs_specs_129	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P33_tags_34[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P33 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P33_tags_34,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P33_tags_34)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P33_tags_34[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P33_tags_34,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P33_tags_34)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P33_tags_34[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_TWIF_ID_ExtIEs_133,
	3,	/* Elements count */
	&asn_SPC_NGAP_TWIF_ID_ExtIEs_specs_133	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P34_tags_35[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P34 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P34_tags_35,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P34_tags_35)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P34_tags_35[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P34_tags_35,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P34_tags_35)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P34_tags_35[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_UEHistoryInformationFromTheUE_ExtIEs_137,
	3,	/* Elements count */
	&asn_SPC_NGAP_UEHistoryInformationFromTheUE_ExtIEs_specs_137	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P35_tags_36[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P35 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P35_tags_36,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P35_tags_36)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P35_tags_36[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P35_tags_36,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P35_tags_36)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P35_tags_36[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_UEIdentityIndexValue_ExtIEs_141,
	3,	/* Elements count */
	&asn_SPC_NGAP_UEIdentityIndexValue_ExtIEs_specs_141	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P36_tags_37[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P36 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P36_tags_37,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P36_tags_37)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P36_tags_37[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P36_tags_37,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P36_tags_37)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P36_tags_37[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_UE_NGAP_IDs_ExtIEs_145,
	3,	/* Elements count */
	&asn_SPC_NGAP_UE_NGAP_IDs_ExtIEs_specs_145	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P37_tags_38[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P37 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P37_tags_38,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P37_tags_38)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P37_tags_38[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P37_tags_38,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P37_tags_38)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P37_tags_38[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_UEPagingIdentity_ExtIEs_149,
	3,	/* Elements count */
	&asn_SPC_NGAP_UEPagingIdentity_ExtIEs_specs_149	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P38_tags_39[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P38 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P38_tags_39,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P38_tags_39)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P38_tags_39[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P38_tags_39,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P38_tags_39)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P38_tags_39[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_UERLFReportContainer_ExtIEs_153,
	3,	/* Elements count */
	&asn_SPC_NGAP_UERLFReportContainer_ExtIEs_specs_153	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P39_tags_40[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P39 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P39_tags_40,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P39_tags_40)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P39_tags_40[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P39_tags_40,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P39_tags_40)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P39_tags_40[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_UPTransportLayerInformation_ExtIEs_157,
	3,	/* Elements count */
	&asn_SPC_NGAP_UPTransportLayerInformation_ExtIEs_specs_157	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P40_tags_41[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P40 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P40_tags_41,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P40_tags_41)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P40_tags_41[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P40_tags_41,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P40_tags_41)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P40_tags_41[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_UserLocationInformation_ExtIEs_161,
	3,	/* Elements count */
	&asn_SPC_NGAP_UserLocationInformation_ExtIEs_specs_161	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P41_tags_42[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P41 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P41_tags_42,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P41_tags_42)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P41_tags_42[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P41_tags_42,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P41_tags_42)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P41_tags_42[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_UserLocationInformationW_AGF_ExtIEs_165,
	3,	/* Elements count */
	&asn_SPC_NGAP_UserLocationInformationW_AGF_ExtIEs_specs_165	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P42_tags_43[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P42 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P42_tags_43,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P42_tags_43)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P42_tags_43[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P42_tags_43,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P42_tags_43)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P42_tags_43[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_W_AGF_ID_ExtIEs_169,
	3,	/* Elements count */
	&asn_SPC_NGAP_W_AGF_ID_ExtIEs_specs_169	/* Additional specs */
};

static const ber_tlv_tag_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P43_tags_44[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_TYPE_descriptor_t asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P43 = {
	"ProtocolIE-SingleContainer",
	"ProtocolIE-SingleContainer",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P43_tags_44,
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P43_tags_44)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P43_tags_44[0]), /* 1 */
	asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P43_tags_44,	/* Same as above */
	sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P43_tags_44)
		/sizeof(asn_DEF_NGAP_ProtocolIE_SingleContainer_9337P43_tags_44[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_WarningAreaList_ExtIEs_173,
	3,	/* Elements count */
	&asn_SPC_NGAP_WarningAreaList_ExtIEs_specs_173	/* Additional specs */
};

