/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/ngap-16.2.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -D /home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/h`
 */

#ifndef	_NGAP_MDTModeNr_H_
#define	_NGAP_MDTModeNr_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NGAP_ImmediateMDTNr.h"
#include "NGAP_LoggedMDTNr.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_MDTModeNr_PR {
	NGAP_MDTModeNr_PR_NOTHING,	/* No components present */
	NGAP_MDTModeNr_PR_immediateMDTNr,
	NGAP_MDTModeNr_PR_loggedMDTNr
	/* Extensions may appear below */
	
} NGAP_MDTModeNr_PR;

/* NGAP_MDTModeNr */
typedef struct NGAP_MDTModeNr {
	NGAP_MDTModeNr_PR present;
	union NGAP_MDTModeNr_u {
		NGAP_ImmediateMDTNr_t	 immediateMDTNr;
		NGAP_LoggedMDTNr_t	 loggedMDTNr;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_MDTModeNr_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_MDTModeNr;
extern asn_CHOICE_specifics_t asn_SPC_NGAP_MDTModeNr_specs_1;
extern asn_TYPE_member_t asn_MBR_NGAP_MDTModeNr_1[2];
extern asn_per_constraints_t asn_PER_type_NGAP_MDTModeNr_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_MDTModeNr_H_ */
#include <asn_internal.h>
