/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/ngap-16.2.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -D /home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/h`
 */

#ifndef	_NGAP_QosCharacteristics_H_
#define	_NGAP_QosCharacteristics_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NGAP_NonDynamic5QIDescriptor.h"
#include "NGAP_Dynamic5QIDescriptor.h"
#include "NGAP_ProtocolIE-SingleContainer.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_QosCharacteristics_PR {
	NGAP_QosCharacteristics_PR_NOTHING,	/* No components present */
	NGAP_QosCharacteristics_PR_nonDynamic5QI,
	NGAP_QosCharacteristics_PR_dynamic5QI,
	NGAP_QosCharacteristics_PR_choice_Extensions
} NGAP_QosCharacteristics_PR;

/* NGAP_QosCharacteristics */
typedef struct NGAP_QosCharacteristics {
	NGAP_QosCharacteristics_PR present;
	union NGAP_QosCharacteristics_u {
		NGAP_NonDynamic5QIDescriptor_t	 nonDynamic5QI;
		NGAP_Dynamic5QIDescriptor_t	 dynamic5QI;
		NGAP_ProtocolIE_SingleContainer_9337P27_t	 choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_QosCharacteristics_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_QosCharacteristics;
extern asn_CHOICE_specifics_t asn_SPC_NGAP_QosCharacteristics_specs_1;
extern asn_TYPE_member_t asn_MBR_NGAP_QosCharacteristics_1[3];
extern asn_per_constraints_t asn_PER_type_NGAP_QosCharacteristics_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_QosCharacteristics_H_ */
#include <asn_internal.h>
