/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/ngap-16.2.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -D /home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/h`
 */

#ifndef	_NGAP_EventTrigger_H_
#define	_NGAP_EventTrigger_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include "NGAP_EventL1LoggedMDTConfig.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_EventTrigger_PR {
	NGAP_EventTrigger_PR_NOTHING,	/* No components present */
	NGAP_EventTrigger_PR_outOfCoverage,
	NGAP_EventTrigger_PR_eventL1LoggedMDTConfig
	/* Extensions may appear below */
	
} NGAP_EventTrigger_PR;
typedef enum NGAP_EventTrigger__outOfCoverage {
	NGAP_EventTrigger__outOfCoverage_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_NGAP_EventTrigger__outOfCoverage;

/* NGAP_EventTrigger */
typedef struct NGAP_EventTrigger {
	NGAP_EventTrigger_PR present;
	union NGAP_EventTrigger_u {
		long	 outOfCoverage;
		NGAP_EventL1LoggedMDTConfig_t	 eventL1LoggedMDTConfig;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_EventTrigger_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_NGAP_outOfCoverage_2;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_EventTrigger;
extern asn_CHOICE_specifics_t asn_SPC_NGAP_EventTrigger_specs_1;
extern asn_TYPE_member_t asn_MBR_NGAP_EventTrigger_1[2];
extern asn_per_constraints_t asn_PER_type_NGAP_EventTrigger_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_EventTrigger_H_ */
#include <asn_internal.h>
