/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/ngap-16.2.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -D /home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/h`
 */

#ifndef	_NGAP_M1ReportingTrigger_H_
#define	_NGAP_M1ReportingTrigger_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_M1ReportingTrigger {
	NGAP_M1ReportingTrigger_periodic	= 0,
	NGAP_M1ReportingTrigger_a2eventtriggered	= 1,
	NGAP_M1ReportingTrigger_a2eventtriggered_periodic	= 2
	/*
	 * Enumeration is extensible
	 */
} e_NGAP_M1ReportingTrigger;

/* NGAP_M1ReportingTrigger */
typedef long	 NGAP_M1ReportingTrigger_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NGAP_M1ReportingTrigger_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_M1ReportingTrigger;
extern const asn_INTEGER_specifics_t asn_SPC_NGAP_M1ReportingTrigger_specs_1;
asn_struct_free_f NGAP_M1ReportingTrigger_free;
asn_struct_print_f NGAP_M1ReportingTrigger_print;
asn_constr_check_f NGAP_M1ReportingTrigger_constraint;
ber_type_decoder_f NGAP_M1ReportingTrigger_decode_ber;
der_type_encoder_f NGAP_M1ReportingTrigger_encode_der;
xer_type_decoder_f NGAP_M1ReportingTrigger_decode_xer;
xer_type_encoder_f NGAP_M1ReportingTrigger_encode_xer;
per_type_decoder_f NGAP_M1ReportingTrigger_decode_uper;
per_type_encoder_f NGAP_M1ReportingTrigger_encode_uper;
per_type_decoder_f NGAP_M1ReportingTrigger_decode_aper;
per_type_encoder_f NGAP_M1ReportingTrigger_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_M1ReportingTrigger_H_ */
#include <asn_internal.h>
