/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/ngap-16.2.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -D /home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/h`
 */

#ifndef	_NGAP_IntersystemSONInformationReport_H_
#define	_NGAP_IntersystemSONInformationReport_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NGAP_InterSystemHOReport.h"
#include "NGAP_InterSystemFailureIndication.h"
#include "NGAP_ProtocolIE-SingleContainer.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_IntersystemSONInformationReport_PR {
	NGAP_IntersystemSONInformationReport_PR_NOTHING,	/* No components present */
	NGAP_IntersystemSONInformationReport_PR_hOReportInformation,
	NGAP_IntersystemSONInformationReport_PR_failureIndicationInformation,
	NGAP_IntersystemSONInformationReport_PR_choice_Extensions
} NGAP_IntersystemSONInformationReport_PR;

/* NGAP_IntersystemSONInformationReport */
typedef struct NGAP_IntersystemSONInformationReport {
	NGAP_IntersystemSONInformationReport_PR present;
	union NGAP_IntersystemSONInformationReport_u {
		NGAP_InterSystemHOReport_t	 hOReportInformation;
		NGAP_InterSystemFailureIndication_t	 failureIndicationInformation;
		NGAP_ProtocolIE_SingleContainer_9337P15_t	 choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_IntersystemSONInformationReport_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_IntersystemSONInformationReport;
extern asn_CHOICE_specifics_t asn_SPC_NGAP_IntersystemSONInformationReport_specs_1;
extern asn_TYPE_member_t asn_MBR_NGAP_IntersystemSONInformationReport_1[3];
extern asn_per_constraints_t asn_PER_type_NGAP_IntersystemSONInformationReport_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_IntersystemSONInformationReport_H_ */
#include <asn_internal.h>
