/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/ngap-16.2.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -D /home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/h`
 */

#ifndef	_NGAP_SONInformation_H_
#define	_NGAP_SONInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NGAP_SONInformationRequest.h"
#include "NGAP_SONInformationReply.h"
#include "NGAP_ProtocolIE-SingleContainer.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_SONInformation_PR {
	NGAP_SONInformation_PR_NOTHING,	/* No components present */
	NGAP_SONInformation_PR_sONInformationRequest,
	NGAP_SONInformation_PR_sONInformationReply,
	NGAP_SONInformation_PR_choice_Extensions
} NGAP_SONInformation_PR;

/* NGAP_SONInformation */
typedef struct NGAP_SONInformation {
	NGAP_SONInformation_PR present;
	union NGAP_SONInformation_u {
		NGAP_SONInformationRequest_t	 sONInformationRequest;
		NGAP_SONInformationReply_t	 sONInformationReply;
		NGAP_ProtocolIE_SingleContainer_9337P29_t	 choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_SONInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_SONInformation;
extern asn_CHOICE_specifics_t asn_SPC_NGAP_SONInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_NGAP_SONInformation_1[3];
extern asn_per_constraints_t asn_PER_type_NGAP_SONInformation_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_SONInformation_H_ */
#include <asn_internal.h>
