/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/ngap-16.2.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -D /home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/h`
 */

#ifndef	_NGAP_ResetType_H_
#define	_NGAP_ResetType_H_


#include <asn_application.h>

/* Including external dependencies */
#include "NGAP_ResetAll.h"
#include "NGAP_UE-associatedLogicalNG-connectionList.h"
#include "NGAP_ProtocolIE-SingleContainer.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_ResetType_PR {
	NGAP_ResetType_PR_NOTHING,	/* No components present */
	NGAP_ResetType_PR_nG_Interface,
	NGAP_ResetType_PR_partOfNG_Interface,
	NGAP_ResetType_PR_choice_Extensions
} NGAP_ResetType_PR;

/* NGAP_ResetType */
typedef struct NGAP_ResetType {
	NGAP_ResetType_PR present;
	union NGAP_ResetType_u {
		NGAP_ResetAll_t	 nG_Interface;
		NGAP_UE_associatedLogicalNG_connectionList_t	 partOfNG_Interface;
		NGAP_ProtocolIE_SingleContainer_9337P28_t	 choice_Extensions;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NGAP_ResetType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ResetType;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_ResetType_H_ */
#include <asn_internal.h>
