/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/ngap-16.2.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -D /home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/h`
 */

#ifndef	_NGAP_ReportAmountMDT_H_
#define	_NGAP_ReportAmountMDT_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum NGAP_ReportAmountMDT {
	NGAP_ReportAmountMDT_r1	= 0,
	NGAP_ReportAmountMDT_r2	= 1,
	NGAP_ReportAmountMDT_r4	= 2,
	NGAP_ReportAmountMDT_r8	= 3,
	NGAP_ReportAmountMDT_r16	= 4,
	NGAP_ReportAmountMDT_r32	= 5,
	NGAP_ReportAmountMDT_r64	= 6,
	NGAP_ReportAmountMDT_rinfinity	= 7
} e_NGAP_ReportAmountMDT;

/* NGAP_ReportAmountMDT */
typedef long	 NGAP_ReportAmountMDT_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NGAP_ReportAmountMDT_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NGAP_ReportAmountMDT;
extern const asn_INTEGER_specifics_t asn_SPC_NGAP_ReportAmountMDT_specs_1;
asn_struct_free_f NGAP_ReportAmountMDT_free;
asn_struct_print_f NGAP_ReportAmountMDT_print;
asn_constr_check_f NGAP_ReportAmountMDT_constraint;
ber_type_decoder_f NGAP_ReportAmountMDT_decode_ber;
der_type_encoder_f NGAP_ReportAmountMDT_encode_der;
xer_type_decoder_f NGAP_ReportAmountMDT_decode_xer;
xer_type_encoder_f NGAP_ReportAmountMDT_encode_xer;
per_type_decoder_f NGAP_ReportAmountMDT_decode_uper;
per_type_encoder_f NGAP_ReportAmountMDT_encode_uper;
per_type_decoder_f NGAP_ReportAmountMDT_decode_aper;
per_type_encoder_f NGAP_ReportAmountMDT_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NGAP_ReportAmountMDT_H_ */
#include <asn_internal.h>
