/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "NGAP-IEs"
 * 	found in "/home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/ngap-16.2.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -D /home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/../openair3/NGAP/MESSAGE/ASN1/R16/h`
 */

#include "NGAP_M1ThresholdEventA2.h"

#include "NGAP_ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_NGAP_M1ThresholdEventA2_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NGAP_M1ThresholdEventA2, threshold_RSRP),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_Threshold_RSRP,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"threshold-RSRP"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NGAP_M1ThresholdEventA2, threshold_RSRQ),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_Threshold_RSRQ,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"threshold-RSRQ"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct NGAP_M1ThresholdEventA2, threshold_SINR),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_Threshold_SINR,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"threshold-SINR"
		},
	{ ATF_POINTER, 1, offsetof(struct NGAP_M1ThresholdEventA2, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NGAP_ProtocolExtensionContainer_9385P116,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_NGAP_M1ThresholdEventA2_oms_1[] = { 3 };
static const ber_tlv_tag_t asn_DEF_NGAP_M1ThresholdEventA2_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NGAP_M1ThresholdEventA2_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* threshold-RSRP */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* threshold-RSRQ */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* threshold-SINR */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_NGAP_M1ThresholdEventA2_specs_1 = {
	sizeof(struct NGAP_M1ThresholdEventA2),
	offsetof(struct NGAP_M1ThresholdEventA2, _asn_ctx),
	asn_MAP_NGAP_M1ThresholdEventA2_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_NGAP_M1ThresholdEventA2_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NGAP_M1ThresholdEventA2 = {
	"M1ThresholdEventA2",
	"M1ThresholdEventA2",
	&asn_OP_SEQUENCE,
	asn_DEF_NGAP_M1ThresholdEventA2_tags_1,
	sizeof(asn_DEF_NGAP_M1ThresholdEventA2_tags_1)
		/sizeof(asn_DEF_NGAP_M1ThresholdEventA2_tags_1[0]), /* 1 */
	asn_DEF_NGAP_M1ThresholdEventA2_tags_1,	/* Same as above */
	sizeof(asn_DEF_NGAP_M1ThresholdEventA2_tags_1)
		/sizeof(asn_DEF_NGAP_M1ThresholdEventA2_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NGAP_M1ThresholdEventA2_1,
	4,	/* Elements count */
	&asn_SPC_NGAP_M1ThresholdEventA2_specs_1	/* Additional specs */
};

