/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "S1AP-IEs"
 * 	found in "/home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/openair3/NGAP/MESSAGES/ASN1/R16/s1ap-15.6.0.asn1"
 * 	`asn1c -pdu=all -fcompound-names -gen-PER -no-gen-OER -no-gen-example -fno-include-deps -D /home/ubuntu/smbshare/work_jftt/zhenghk/test/THREAD-new/cmake_targets/build_dir/build/CMakeFiles/NGAP_R16`
 */

#ifndef	_S1AP_TargetID_H_
#define	_S1AP_TargetID_H_


#include <asn_application.h>

/* Including external dependencies */
#include "S1AP_TargeteNB-ID.h"
#include "S1AP_TargetRNC-ID.h"
#include "S1AP_CGI.h"
#include "S1AP_TargetNgRanNode-ID.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum S1AP_TargetID_PR {
	S1AP_TargetID_PR_NOTHING,	/* No components present */
	S1AP_TargetID_PR_targeteNB_ID,
	S1AP_TargetID_PR_targetRNC_ID,
	S1AP_TargetID_PR_cGI,
	/* Extensions may appear below */
	S1AP_TargetID_PR_targetgNgRanNode_ID
} S1AP_TargetID_PR;

/* S1AP_TargetID */
typedef struct S1AP_TargetID {
	S1AP_TargetID_PR present;
	union S1AP_TargetID_u {
		S1AP_TargeteNB_ID_t	 targeteNB_ID;
		S1AP_TargetRNC_ID_t	 targetRNC_ID;
		S1AP_CGI_t	 cGI;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
		S1AP_TargetNgRanNode_ID_t	 targetgNgRanNode_ID;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} S1AP_TargetID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_S1AP_TargetID;

#ifdef __cplusplus
}
#endif

#endif	/* _S1AP_TargetID_H_ */
#include <asn_internal.h>
